### ISSUE TITLE
Touchscreen only, or also touchpad

### ISSUE THREAD

**Issue by superm1** [PaulLiang01043/elan_i2chid_tools#1]
Hi,

I was wondering - are these tools only for Elan touchscreen or would they also work for Elan Touchpad?

Or is Elan touchpad only supposed to use kernel interface for updating?

**Comment by PaulLiang01043** [comment]
Hi superm1,

This tool is only for Elan touchscreen.
It can not be used to update firmware for Elan touchpad.

BR,
Paul
